### PR TITLE
pull out decoded ID for hashedFields

### PR DESCRIPTION
**Pull request by jakeorr**
Hello! 👋   

First off, thanks for the handy project. It's been great to use so far.

I noticed an issue related to the hashedFields static model property. It seemed like the hashed fields we being respected, but the decoding wasn't happening properly.

I built a project to reproduce the issue and to try out the fix. More description in the readme: https://github.com/jakeorr/objection-hashid-investigation

### CODE REVIEW

**Comment by JaneJeon** [comment]
Huh, I'm actually surprised it somehow didn't break on my own codebases (which uses objection-hashid).

Thanks for the easy reproduction, I'll be sure to add test cases covering this.

**Comment by JaneJeon** [comment]
I will upload the fixed version to npm as soon as I can write a test for it.

**Comment by jakeorr** [comment]
Sounds great, thanks @JaneJeon!

**Comment by JaneJeon** [comment]
It's already been uploaded to npm, so just bump your version of objection-hashid!

**Pull request merged**
