### PR TITLE
Add type declarations (resolve #46)

### LINKED ISSUE #46: TypeScript type declaration file
Similar to my proposal left on your [objection-authorize repo](https://github.com/JaneJeon/objection-authorize/issues/1), would you be willing to let me add a type declaration file to this project?

### PR DESCRIPTION
**Pull request by olavim**
Follow-up on https://github.com/JaneJeon/objection-hashid/pull/51

### CODE REVIEW

**Comment by JaneJeon** [comment]
Hey, I'm _really_ sorry for how freaking LONG it's taken me to get around this (I blame ADHD!). So I tried out your `index.d.ts`, and while it _looks_ correct, when I look at the `index.d.ts` in VSCode, I see the same dreaded problem I've been trying to solve in the other PR: overriding `SomeModel.query()`.

It looks like you've tried some fancy stuff above and beyond what the objection docs basically told you to do, and it appears that other than minor nitpicks (e.g. typescript does not pick up `import { foo } from 'objection-2'`, only `import {foo} from 'objection'` after I've `npm i -D objection`'d, and some of the imports are unused), it seems like the reason `Model.query()` still refusing to be typed is because the previous plugin (objection-visibility) _also_ touches `QueryBuilder`.

At this point, I'm really not sure what to do. As documented in #51 and https://github.com/Vincit/objection.js/issues/1589, TypeScript just seems to shit the bed when it comes to multiple plugins. I'm honestly tempted to just merge this and call it a day, I don't know where to proceed from here. If you have any suggestions for what I should do @olavim, I'd greatly appreciate it.

**Comment by JaneJeon** [comment]
Oh, and one more thing I've noticed (the same with #51 if you're still alive @geopic) - even when I fix aforementioned errors, there are two areas where even this solution falls short:
1. You don't get _any_ sort of typing on `.query()`. Sure, typescript won't _fail_ the code, but considering that (at least for me) the whole point of using ts definitions is to get completions on your IDE, the fact that not even
```js
class BaseBaseModel extends plugin(Model) {
    static get tableName() {
      return `table1-${version}`
    }
  }
await BaseModel.query() // <----- here
```
this gets typed, it's really unfortunate.
2. So while typescript doesn't screech at `await BaseModel.query()...`, it DOES yell at me for trying `await AlgoliaObject.query()` or `await HiddenId.query()`, or hell, even `await ModelA.query()` (which doesn't even touch any `hashId-x` properties!) So I'm guessing _inheriting_ from the base class causes `SubClass.query()` to cause a type error. So the types, again, don't work here :(

A few "fun facts" about the inheritance:
1. This isn't a problem with multiple plugins touching the `QueryBuilder`, because even when I set `BaseClass` as literally just `plugin(Model)` (i.e. only one layer), I still get the same error.
2. 
```js
const modelA = await ModelA.query().insertAndFetch({})
```
errors, but not
```js
const modelB = await modelA.$relatedQuery('modelBs').insert({})
```
🤔

**Comment by olavim** [comment]
@JaneJeon I don't really remember the minor details anymore, but if Objection's type system and TypeScript's capabilities haven't improved by leaps and bounds, I suggest you give up on this completely. Trying to get _proper_ query builder typings is impossible, and even partial support is a metaphorical hydra: If you solve one issue with the types, you will also create at least one new problem. Even if you assume there are no other plugins, it's impossible to guarantee your types work in all cases given all the trickery you can do with Objection. If there is some other plugin that modifies the query builder, you're straight out of luck.

Heed my advice and don't add types to the query builder. You can add type to options you can give to the plugin though, if you have those 😄

**Comment by JaneJeon** [comment]
RIP the dreams. Thank you very much for giving this a _proper_ crack, at least!

**Comment by geopic** [comment]
It was worth a shot.

**Pull request closed without merging**
